version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db_container
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=map-project
      - POSTGRES_DB=map-project-db
      - POSTGRES_PASSWORD=map-project
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - map-project-network

networks:
  map-project-network:
    name: map-project-network
